# Generated by Django 4.1.13 on 2023-12-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=2550)),
                ('national_id', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('school', models.CharField(max_length=255)),
                ('instructor_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=2550)),
                ('national_id', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('school', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('major', models.CharField(choices=[('CSAI', 'Csai'), ('Business', 'Business'), ('Science', 'Science'), ('Engineering', 'Engineering')], max_length=255)),
                ('concentration', models.CharField(choices=[('SWD', 'Swd'), ('DSAI', 'Dsai'), ('IT', 'It'), ('Business', 'Business'), ('BMS', 'Bms'), ('Physics', 'Physics'), ('Nanotechnology', 'Nanotechnology'), ('NanoScience', 'Nanoscience'), ('Envirmontal', 'Envirmontal'), ('Renewable', 'Renewable'), ('CIE', 'Cie'), ('Aerospace', 'Aerospace')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
                ('field2', models.IntegerField()),
            ],
        ),
    ]
