# Generated by Django 4.1.13 on 2023-12-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_subject_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ESSAY', 'Essay')], max_length=5)),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard'), ('Unbelievably Hard', 'Unbelievably Hard'), ('Eb2a 2abelny lw 7aleto', 'Eb2a 2abelny lw 7aleto'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('grades', models.ManyToManyField(through='back_end.Grade', to='back_end.student')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.instructor')),
                ('questions', models.ManyToManyField(to='back_end.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.subject')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.quiz'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.student'),
        ),
    ]
