# Generated by Django 4.1.13 on 2023-12-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_grade_question_quiz_grade_quiz_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
